DETS_TXT: /MS3D/tools/cfgs/target_waymo/label_generation/round1/cfgs/ensemble_detections.txt
SAVE_DIR: /MS3D/tools/cfgs/target_waymo/label_generation/round1/ps_labels
DATA_CONFIG_PATH: /MS3D/tools/cfgs/dataset_configs/waymo_dataset_da.yaml

PS_SCORE_TH: # veh,ped,cyc
  POS_TH: [0.7,0.6,0.5]
  NEG_TH: [0.3,0.2,0.2]

ENSEMBLE_KBF:
  DISCARD: [4, 4, 4]
  RADIUS: [1.5, 0.3, 0.2]
  NMS: [0.1, 0.3, 0.1]

TRACKING:
  VEH_ALL:
    RUNNING:
        SCORE_TH: 0.6
        MAX_AGE_SINCE_UPDATE: 2
        MIN_HITS_TO_BIRTH: 2
        ASSO: giou
        ASSO_TH: 1.0
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: 0.1
  VEH_STATIC:
    RUNNING:
        SCORE_TH: 0.5
        MAX_AGE_SINCE_UPDATE: 4
        MIN_HITS_TO_BIRTH: 2
        ASSO: iou_2d
        ASSO_TH: 0.7
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: 0.5
  PEDESTRIAN:
    RUNNING:
        SCORE_TH: 0.2
        MAX_AGE_SINCE_UPDATE: 2
        MIN_HITS_TO_BIRTH: 2
        ASSO: giou
        ASSO_TH: 0.8
    REDUNDANCY:
        SCORE_TH: 0.1
        MAX_REDUNDANCY_AGE: 3
        ASSO_TH: 0.2

TEMPORAL_REFINEMENT:
  TRACK_FILTERING:
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_VEH_ALL: 4
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_VEH_STATIC: 2
    MIN_DETS_ABOVE_POS_TH_FOR_TRACKS_PED: 2
    USE_STATIC_PED_TRACKS: false
    MIN_NUM_STATIC_VEH_TRACKS: 10
    MIN_NUM_PED_TRACKS: 10
  ROLLING_KBF:
    MIN_STATIC_SCORE: 0.75
    ROLLING_KDE_WINDOW: 16
  PROPAGATE_BOXES:
    MIN_STATIC_TRACKS: 24
    N_EXTRA_FRAMES: 100
    DEGRADE_FACTOR: 0.98
    MIN_SCORE_CLIP: 0.5
